name: Deploy Astro site to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
env:
  BUILD_PATH: "." # default value when not using subfolders
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build with Astro
        run: npm run build
        env:
          #BASE_URL: '/acousphem.github.io/' # Asegúrate de reemplazar con el nombre de tu repositorio
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1